# Generated by Django 3.2.6 on 2021-10-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='consumption_records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.IntegerField()),
                ('level', models.IntegerField()),
                ('consumption', models.IntegerField()),
                ('staff_count', models.IntegerField()),
                ('resource_running', models.IntegerField()),
                ('hours_usage', models.IntegerField()),
                ('resource_idling', models.IntegerField()),
            ],
        ),
    ]
